---
name: Epic Status Update REQUIRED
description: Weekly status update for Epics
body:
  - type: dropdown
    attributes:
      required: true
      label: Status
      options:
        - label: "🟢 GREEN (All good, smooth sailing)"
          value: "Status: GREEN"
        - label: "⚠️ YELLOW (At risk, heads-up)"
          value: "Status: YELLOW"
        - label: "🚨 RED (BLOCKED)"
          value: "Status: RED"
