---
name: Basic form
description: File a bug report github/DIY-3
title: "[Bug]: "
labels: ["bug", "DEFINITELY-INVALID"]
assignees:
  - monalisa
body:
  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  
