name: Feature request
description: Suggest a new feature for Flame.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        When suggesting a feature, please read this complete form and fill in all the questions in order to get a better response!
  - type: textarea
    id: problem-to-solve
    attributes:
      label: Problem to solve
      description: Which problem would be solved with this feature?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What do you propose as a solution? Add as much information as you can!
    validations:
      required: true
  - type: textarea
    id: more-information
    attributes:
      label: More information
      description: Do you have any other useful information about this feature report? Please write it down here. Possible helpful information: references to other sites/repositories
  - type: checkbox
    id: interested-in-pr
    attributes:
      label: Are you interested in working on a PR for this?
      
