---
name: No quotes
description: Weekly status update for Epics
body:
  - type: dropdown
    attributes:
      label: Status
      options:
        - "🟢 GREEN (All good, smooth sailing)"
        - "⚠️ YELLOW (At risk, heads-up)"
        - "🚨 RED (BLOCKED)"
