---
name: No quotes MULTIPLE
description: Weekly status update for Epics
body:
  - type: dropdown
    attributes:
      label: Status
      options:
        - "🟢 GREEN (All good, smooth sailing)"
        - "⚠️ YELLOW (At risk, heads-up)"
        - "🚨 RED (BLOCKED)"
  - type: dropdown
    attributes:
      multiple: true
      label: Status 2
      options:
        - "🟢 GREEN (All good, smooth sailing)"
        - "⚠️ YELLOW (At risk, heads-up)"
        - "🚨 RED (BLOCKED)"
  - type: dropdown
    attributes:
      multiple: true
      label: Status 3
      options:
        - "🟢 GREEN (All good, smooth sailing)"
        - "⚠️ YELLOW (At risk, heads-up)"
        - "🚨 RED (BLOCKED)"
    validations:
      required: true
